# fly.toml app configuration file generated for github-action-demo on 2023-07-31T11:27:27+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "github-action-demo"
primary_region = "hkg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
